[package]
name = "ccwc"
version = "0.2.0"
edition = "2021"
authors = ["Michael Eberhardt <github@michael-eberhardt.de>"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }

[dev-dependencies]
totems = "0.2"
