[package]
name = "cccompress"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
clap = { version = "4.4", features = ["derive"] }

[dev-dependencies]
crossterm = "0.27.0"
ratatui = "0.25.0"
totems = "0.2"
