[package]
name = "ccwebserv"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
clap = "4.4.18"
tokio = { version = "1.36.0", features = ["full"] }
